namespace DLA_to_Excel
{
    public class FLISFOI
    {
        public string FSG_3994 { get; set; }
        public string FSC_WI_FSG_3996 { get; set; }
        public string NCB_CD_4130 { get; set; }
        public string I_I_NBR_4131 { get; set; }
        public string FIIG_4065 { get; set; }
        public string INC_4080 { get; set; }
        public string SHRT_NM_2301 { get; set; }
        public string NAIN_5020 { get; set; }
        public string CRITL_CD_FIIG_3843 { get; set; }
        public string TYP_II_4820 { get; set; }
        public string RPDMRC_4765 { get; set; }
        public string DEMIL_CD_0167 { get; set; }
        public string DT_NIIN_ASGMT_2180 { get; set; }
        public string HMIC_0865 { get; set; }
        public string ESD_EMI_CD_2043 { get; set; }
        public string PMIC_0802 { get; set; }
        public string ADPEC_0801 { get; set; }
        public string MOE_RULE_NBR_8290 { get; set; }
        public string AMC_2871 { get; set; }
        public string AMSC_2876 { get; set; }
        public string NIMSC_0076 { get; set; }
        public string EFF_DT_2128 { get; set; }
        public string IMC_2744 { get; set; }
        public string IMC_ACTY_2748 { get; set; }
        public string DSOR_0903 { get; set; }
        public string SUPPLM_COLLBR_2533 { get; set; }
        public string SUPPLM_RCVR_2534 { get; set; }
        public string AAC_2507 { get; set; }
        public string FMR_MOE_RULE_8280 { get; set; }
        public string RNFC_2920 { get; set; }
        public string RNCC_2910 { get; set; }
        public string RNVC_4780 { get; set; }
        public string DAC_2640 { get; set; }
        public string RNAAC_2900 { get; set; }
        public string RNSC_2923 { get; set; }
        public string RNJC_2750 { get; set; }
        public string CAGE_CD_9250 { get; set; }
        public string REF_NBR_3570 { get; set; }
        public string SADC_4672 { get; set; }
        public string HCC_2579 { get; set; }
        public string MSDS_ID_9076 { get; set; }
        public string ISC_2650 { get; set; }
        public string ORG_STDZN_DEC_9325 { get; set; }
        public string DT_STDZN_DEC_2300 { get; set; }
        public string NIIN_STAT_CD_2670 { get; set; }
        public string RP_NSN_STD_RL_8977_RPLM_NSN_STDZ_9525 { get; set; }
        public string RP_ISC_2650 { get; set; }
        public string RP_ORG_STDZN_DEC_9325 { get; set; }
        public string RP_DT_STDZN_DEC_2300 { get; set; }
        public string RP_NIIN_STAT_CD_2670 { get; set; }
        public string INTGTY_CD_0864 { get; set; }
        public string ORIG_ACTY_CD_4210 { get; set; }
        public string RAIL_VARI_CD_4760 { get; set; }
        public string NMFC_2850 { get; set; }
        public string SUB_ITM_NBR_0861 { get; set; }
        public string UFC_CD_MODF_3040 { get; set; }
        public string HMC_2720 { get; set; }
        public string LCL_CD_2760 { get; set; }
        public string WRT_CMDTY_CD_9275 { get; set; }
        public string TYPE_CGO_CD_9260 { get; set; }
        public string SP_HDLG_CD_9240 { get; set; }
        public string AIR_DIM_CD_9220 { get; set; }
        public string AIR_CMTY_HDLG_9215 { get; set; }
        public string CLAS_RTNG_CD_2770 { get; set; }
        public string FRT_DESC_4020 { get; set; }
        public string MOE_CD_2833 { get; set; }
        public string SOS_CD_3690_OR_SOSM_CD_2948 { get; set; }
        public string QUP_6106 { get; set; }
        public string UI_3050 { get; set; }
        public string UNIT_PR_7075 { get; set; }
        public string DOLLAR_AMOUNT { get; set; }
        public string CENTS_AMOUNT { get; set; }
        public string SLC_2943 { get; set; }
        public string CIIC_2863 { get; set; }
        public string REP_CD_DLA_2934 { get; set; }
        public string REP_CD_CG_0709 { get; set; }
        public string ERRC_CD_AF_2655 { get; set; }
        public string RECOV_CD_MC_2891 { get; set; }
        public string RECOV_CD_AR_2892 { get; set; }
        public string MAT_CTL_NVY_2832 { get; set; }
        public string MGMT_CONTROL_DATA { get; set; }
        public string MAJ_MCC_AR_9256 { get; set; }
        public string AR_MCC_AP_SUB_2163 { get; set; }
        public string AR_MCC_USE_CD_2161 { get; set; }
        public string AR_MCC_SG_CD1_2167 { get; set; }
        public string ACTG_RQMT_AR_2665 { get; set; }
        public string FILLER { get; set; }
        public string FUND_CD_AF_2695 { get; set; }
        public string BDGT_CD_AF_3765 { get; set; }
        public string MMAC_AF_2836 { get; set; }
        public string PVC_AF_0858 { get; set; }
        public string STRS_ACT_MC_2959 { get; set; }
        public string CMBT_ESTL_MC_3311 { get; set; }
        public string MAT_MGMT_MC_9257 { get; set; }
        public string ECH_CD_MC_3150 { get; set; }
        public string MAT_IDEN_MC_4126 { get; set; }
        public string OPRTL_TST_MC_0572 { get; set; }
        public string PHY_CTGY_MC_0573 { get; set; }
        public string COG_CD_NVY_2608 { get; set; }
        public string SMIC_NVY_2834 { get; set; }
        public string IRRC_NVY_0132 { get; set; }
        public string SP_MAT_CONT_0121 { get; set; }
        public string INV_ACT_CG_0708 { get; set; }
        public string SER_NO_CTL_CG_0763 { get; set; }
        public string USI_SVC_CD_0745 { get; set; }
        public string UI_CONV_FAC_3053 { get; set; }
        public string PHRS_CD_2862 { get; set; }
        public string PHRS_CD_PHRS_5240 { get; set; }
        public string QTY_PER_ASBL_0106 { get; set; }
        public string UNIT_MEAS_CD_0107 { get; set; }
        public string OOU_0793 { get; set; }
        public string JTC_0792 { get; set; }
        public string PK_DTA_SRC_CD_5148 { get; set; }
        public string PICA_SICA_IND_5099 { get; set; }
        public string INTMD_CTN_QTY_5152 { get; set; }
        public string UP_WT_5153 { get; set; }
        public string UP_SZ_5154 { get; set; }
        public string UP_CU_5155 { get; set; }
        public string PKG_CTGY_CD_5159 { get; set; }
        public string ITM_TYP_STOR_5156 { get; set; }
        public string UNPKG_ITM_WT_5157 { get; set; }
        public string UNPKG_ITM_DIM_5158 { get; set; }
        public string MTHD_PRSRV_CD_5160 { get; set; }
        public string CLNG_DRY_PRC_5161 { get; set; }
        public string PRSRV_MAT_CD_5162 { get; set; }
        public string WRAP_MAT_CD_5163 { get; set; }
        public string CUSH_DUN_MAT_5164 { get; set; }
        public string THK_CUSH_DUN_5165 { get; set; }
        public string UNIT_CTNR_CD_5166 { get; set; }
        public string INTMD_CTNR_CD_5167 { get; set; }
        public string UNIT_CTNR_LVL_5168 { get; set; }
        public string SP_MKG_CD_5169 { get; set; }
        public string LVL_A_PKG_CD_5170 { get; set; }
        public string LVL_B_PKG_CD_5171 { get; set; }
        public string OPTNL_PRO_IND_5173 { get; set; }
        public string SUPMTL_INST_5174 { get; set; }
        public string SPI_NBR_5175 { get; set; }
        public string SPI_REV_5176 { get; set; }
        public string SPI_DT_5177 { get; set; }
        public string CTNR_NSN_5178 { get; set; }
        public string PKG_DSGN_ACTY_5179 { get; set; }
        public string MINM_PK_RQ_CD_5172 { get; set; }
    }
}